name:                pie
version:             0.1.0.0
github:              "ghost-not-in-the-shell/pie"
license:             BSD3
author:              "gnits"
maintainer:          "ghost.not.in.the.shell@gmail.com"

description:         "Toy dependent type language for learning purpose"

default-extensions:
- DerivingVia
- DuplicateRecordFields
- LambdaCase
- PatternSynonyms
- UnicodeSyntax
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- parsec
- pretty

ghc-options:
- -W

library:
  source-dirs: src

executables:
  pie-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - pie

tests:
  pie-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - pie
      - tasty
      - tasty-hunit
